### ISSUE TITLE
Pinned tab issue with FF29

### ISSUE THREAD

**Issue by spvkgn** [ithinc/tabutils#90]
I have several pinned tabs and when I adding a new pinned tab this added tab attaches to the left end tab position. While with disabled TU extension this tab attaches to the next position after right end pinned tab - as intended.
I tried with 1.5.28.1 and with latest development beta version - both has this issue.

**Comment by Kamui-Solo** [comment]
It's all related to "phantom pinned tabs", it was always buggy, even if disabled :angry: 
Ithinc, may be it's time to remove this feature?

**Comment by Geobert** [comment]
I confirm this issue Ffx 30 beta, 1.5.28.1 or latest dev version. Windows version.
EDIT: just tested with extensions.tabutils.pinTab.showPhantom set to false and it workarounds the bug

**Comment by seals55** [comment]
Broke for me when 31.0 was pushed to my win8.1 box. Had to disable plugin to see pinned tabs and recover inches of blank space.

**Comment by Archenoth** [comment]
I find that whenever this happened, that [Right Click]ing the phantom tab space and selecting "Open all in tabs" allows me to get a handle on the tabs again, allowing me to unpin and close them.

Phantom tabs were quite useful for things like /quitting out of a fullscreen Chatzilla or otherwise forcefully closing them. It would let you resume right back from the Tab's location with all of the tab settings intact. But as of 30 on Linux Mint 17 (64-bit), there have been some pretty gnarly issues with phantoms becoming a tad bit more dead than expected.

**Comment by teksean** [comment]
The Phantom Pinned tab feature does not work anymore.
I miss having my tabs pinned yet closed when I am not using them. It helps out with memory used by browser by not having them all active when I do not need them. Now, if I try to do that, I get a void space that keeps stretching across the tab bar. I had to go into "about:config" page, look up Phantom and disable the feature.
I am very sad that it does not work any more. Please restore it. Thank you.

"Australis theme messes up Phantom tabs, which will be addressed later." was stated in issue <a>https://github.com/ithinc/tabutils/issues/28</a>. When would that be addressed?

**Comment by yfdyh000** [comment]
Please try the https://github.com/yfdyh000/tabutils/releases 2015.02.12 and report any problem.
